"""add rejection_reason to document

Revision ID: 19784fa30330
Revises: 67503ab82de7
Create Date: 2026-06-04 06:16:04.698619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19784fa30330'
down_revision: Union[str, None] = '67503ab82de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('academic_years_label_key', 'academic_years', type_='unique')
    op.drop_index('ix_academic_years_label', table_name='academic_years')
    op.create_index(op.f('ix_academic_years_label'), 'academic_years', ['label'], unique=True)
    op.drop_constraint('courses_code_key', 'courses', type_='unique')
    op.drop_index('ix_courses_code', table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.drop_constraint('departments_code_key', 'departments', type_='unique')
    op.drop_index('ix_departments_code', table_name='departments')
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.drop_constraint('document_types_name_key', 'document_types', type_='unique')
    op.drop_index('ix_document_types_name', table_name='document_types')
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=True)
    op.add_column('documents', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint('universities_code_key', 'universities', type_='unique')
    op.drop_constraint('universities_name_key', 'universities', type_='unique')
    op.drop_index('ix_universities_code', table_name='universities')
    op.create_index(op.f('ix_universities_code'), 'universities', ['code'], unique=True)
    op.drop_index('ix_universities_name', table_name='universities')
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.create_index('ix_universities_name', 'universities', ['name'], unique=False)
    op.drop_index(op.f('ix_universities_code'), table_name='universities')
    op.create_index('ix_universities_code', 'universities', ['code'], unique=False)
    op.create_unique_constraint('universities_name_key', 'universities', ['name'])
    op.create_unique_constraint('universities_code_key', 'universities', ['code'])
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('documents', 'rejection_reason')
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.create_index('ix_document_types_name', 'document_types', ['name'], unique=False)
    op.create_unique_constraint('document_types_name_key', 'document_types', ['name'])
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.create_index('ix_departments_code', 'departments', ['code'], unique=False)
    op.create_unique_constraint('departments_code_key', 'departments', ['code'])
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index('ix_courses_code', 'courses', ['code'], unique=False)
    op.create_unique_constraint('courses_code_key', 'courses', ['code'])
    op.drop_index(op.f('ix_academic_years_label'), table_name='academic_years')
    op.create_index('ix_academic_years_label', 'academic_years', ['label'], unique=False)
    op.create_unique_constraint('academic_years_label_key', 'academic_years', ['label'])
    # ### end Alembic commands ###
